repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language: system
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language: system
        args: [--check]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language: system
        args: [--check-only]
